# Generated by Django 3.2.12 on 2022-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Image',
            field=models.FileField(max_length=150, null=True, upload_to=''),
        ),
    ]
