# Generated by Django 3.2.12 on 2022-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitization', '0002_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='UpdationDate',
            field=models.DateField(null=True),
        ),
    ]
