# Generated by Django 3.2.12 on 2022-02-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitization', '0003_alter_tracking_updationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
