# Generated by Django 4.1.3 on 2023-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitization', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=500)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
